import '../../../Models/customModel/mango_tags.dart';

final List<MangoTags> loadedTags = [
  MangoTags(id: '1', title: "Novels"),
  MangoTags(id: '2', title: 'Short stories'),
  MangoTags(id: '3', title: 'Creative essay'),
  MangoTags(id: '4', title: 'Poetry'),
  MangoTags(id: '5', title: 'Copywriting'),
  MangoTags(id: '6', title: 'Feature stories'),
  MangoTags(id: '7', title: 'Prose'),
  MangoTags(id: '8', title: 'Drama'),
  MangoTags(id: '9', title: 'Non-fiction'),
  MangoTags(id: '10', title: 'Adventure'),
  MangoTags(id: '11', title: 'Fairy tales'),
  MangoTags(id: '12', title: 'Sci-fi'),
  MangoTags(id: '13', title: 'Fantasy'),
  MangoTags(id: '14', title: 'Folklore'),
  MangoTags(id: '15', title: 'Craft and hobbies'),
  MangoTags(id: '16', title: 'Science and technology'),
  MangoTags(id: '17', title: 'Religion'),
  MangoTags(id: '18', title: 'News writing'),
  MangoTags(id: '19', title: 'Content writers'),
  MangoTags(id: '20', title: 'Hiphop'),
  MangoTags(id: '21', title: 'Dance'),
  MangoTags(id: '22', title: 'Soul'),
  MangoTags(id: '23', title: 'Jazz'),
  MangoTags(id: '24', title: 'RnB'),
  MangoTags(id: '25', title: 'EDM'),
  MangoTags(id: '26', title: 'Grime'),
  MangoTags(id: '27', title: 'Apala'),
  MangoTags(id: '28', title: 'Sakara'),
  MangoTags(id: '29', title: 'House'),
  MangoTags(id: '30', title: 'Electro'),
  MangoTags(id: '31', title: 'Rock'),
  MangoTags(id: '32', title: 'Pop'),
  MangoTags(id: '33', title: 'Afrobeats'),
  MangoTags(id: '34', title: 'Afrohouse'),
  MangoTags(id: '35', title: 'Afrosoul'),
  MangoTags(id: '36', title: 'Afro-pop'),
  MangoTags(id: '37', title: 'Trap'),
  MangoTags(id: '38', title: 'Blues'),
  MangoTags(id: '39', title: 'Raggae'),
  MangoTags(id: '40', title: 'Techno'),
  MangoTags(id: '41', title: 'Instrumentals'),
  MangoTags(id: '42', title: 'Indie'),
  MangoTags(id: '43', title: 'Fuji'),
  MangoTags(id: '44', title: 'Juju'),
  MangoTags(id: '45', title: 'Highlife'),
  MangoTags(id: '46', title: 'Gospel'),
  MangoTags(id: '47', title: 'Lullaby'),
  MangoTags(id: '48', title: 'Ethnics'),
  MangoTags(id: '49', title: 'metaphysics'),
  MangoTags(id: '50', title: 'Aesthetics'),
  MangoTags(id: '51', title: 'Logic'),
  MangoTags(id: '52', title: 'Phenomenology'),
  MangoTags(id: '53', title: 'Philosophy of religion'),
  MangoTags(id: '54', title: 'Charles Dawin'),
  MangoTags(id: '55', title: 'Aristotle'),
  MangoTags(id: '56', title: 'Plato'),
  MangoTags(id: '57', title: 'Socrates'),
  MangoTags(id: '58', title: 'Pythagoras'),
  MangoTags(id: '59', title: 'Humanism'),
  MangoTags(id: '60', title: 'Philosophy and science'),
  MangoTags(id: '61', title: 'Philosophy and technology'),
  MangoTags(id: '62', title: 'Social sciences'),
  MangoTags(id: '63', title: 'Pure science'),
  MangoTags(id: '64', title: 'Applied science'),
  MangoTags(id: '65', title: 'Humanism'),
  MangoTags(id: '66', title: 'Humanism'),
  MangoTags(id: '67', title: 'Humanism'),
  MangoTags(id: '68', title: 'Humanism'),
  MangoTags(id: '69', title: 'Humanism'),
  MangoTags(id: '70', title: 'Humanism'),
  MangoTags(id: '71', title: 'Behavior'),
  MangoTags(id: '72', title: 'Child improvement'),
  MangoTags(id: '73', title: 'Depression'),
  MangoTags(id: '74', title: 'Ageing'),
  MangoTags(id: '75', title: 'Anxiety'),
  MangoTags(id: '76', title: 'Applied Pyschology'),
  MangoTags(id: '77', title: 'Autism'),
  MangoTags(id: '78', title: 'Sleep'),
  MangoTags(id: '79', title: 'Decision-making'),
  MangoTags(id: '80', title: 'Ballet'),
  MangoTags(id: '81', title: 'Bars'),
  MangoTags(id: '82', title: 'Concerts'),
  MangoTags(id: '83', title: 'Dancehalls'),
  MangoTags(id: '84', title: 'Music festivals'),
  MangoTags(id: '85', title: 'Nightclubs'),
  MangoTags(id: '86', title: 'Parties'),
  MangoTags(id: '87', title: 'Plays'),
  MangoTags(id: '88', title: 'Theatre'),
  MangoTags(id: '89', title: 'Physical sports'),
  MangoTags(id: '90', title: 'Football'),
  MangoTags(id: '91', title: 'Basketball'),
  MangoTags(id: '92', title: 'Tennis'),
  MangoTags(id: '93', title: 'Table tennis'),
  MangoTags(id: '94', title: 'Lawn tennis'),
  MangoTags(id: '95', title: 'Volleyball'),
  MangoTags(id: '96', title: 'Golf'),
  MangoTags(id: '97', title: 'Hockey'),
  MangoTags(id: '98', title: 'Marathon'),
  MangoTags(id: '99', title: 'Formula 1'),
  MangoTags(id: '100', title: 'Track and field sports'),
  MangoTags(id: '101', title: 'Indoor sports'),
  MangoTags(id: '103', title: 'Baseball'),
  MangoTags(id: '103', title: 'Cricket'),
  MangoTags(id: '104', title: 'Boxing'),
  MangoTags(id: '105', title: 'Wrestling'),
  MangoTags(id: '106', title: 'Athletics'),
  MangoTags(id: '107', title: 'Cycling'),
  MangoTags(id: '108', title: 'Badminton'),
  MangoTags(id: '109', title: 'Recreational'),
  MangoTags(id: '110', title: 'Yoga'),
  MangoTags(id: '111', title: 'Swimming'),
  MangoTags(id: '112', title: 'Running'),
  MangoTags(id: '113', title: 'Beach racing'),
  MangoTags(id: '114', title: 'Bike'),
  MangoTags(id: '115', title: 'Skating'),
  MangoTags(id: '116', title: 'Surfing'),
  MangoTags(id: '117', title: 'Exercises & workout'),
  MangoTags(id: '118', title: 'Camping'),
  MangoTags(id: '119', title: 'Surfing'),
  MangoTags(id: '120', title: 'Bet'),
  MangoTags(id: '121', title: 'Bet9ja'),
  MangoTags(id: '122', title: 'Nairabet'),
  MangoTags(id: '123', title: 'KingsBet'),
  MangoTags(id: '124', title: 'SportyBet'),
  MangoTags(id: '125', title: '1x Bet'),
  MangoTags(id: '126', title: 'Virtual betting'),
  MangoTags(id: '127', title: 'Davido'),
  MangoTags(id: '128', title: 'Wizkid'),
  MangoTags(id: '129', title: 'Burna boy'),
  MangoTags(id: '130', title: 'Don jazzy'),
  MangoTags(id: '131', title: 'Olamide'),
  MangoTags(id: '132', title: 'Phyno'),
  MangoTags(id: '133', title: 'Tiwa savage'),
  MangoTags(id: '134', title: 'Tems'),
  MangoTags(id: '135', title: 'Niniola'),
  MangoTags(id: '136', title: 'Dbanj'),
  MangoTags(id: '137', title: 'Tuface'),
  MangoTags(id: '138', title: 'Mercy Johnson'),
  MangoTags(id: '139', title: 'Funke Akindele'),
  MangoTags(id: '140', title: 'Desmond Eliot'),
  MangoTags(id: '141', title: 'Ramsey Noah'),
  MangoTags(id: '142', title: 'Aki & Pawpaw'),
  MangoTags(id: '143', title: 'Ruger'),
  MangoTags(id: '144', title: 'Rema'),
  MangoTags(id: '145', title: 'Ayra Starr'),
  MangoTags(id: '146', title: 'Buju'),
  MangoTags(id: '147', title: 'Bobby Shmurda'),
  MangoTags(id: '148', title: 'Seyi Shay'),
  MangoTags(id: '149', title: 'Chidinma Ekile'),
  MangoTags(id: '150', title: 'Naira Marley'),
  MangoTags(id: '151', title: 'Destiny Etiko'),
  MangoTags(id: '152', title: 'Zubby Michael'),
  MangoTags(id: '153', title: 'Pere'),
  MangoTags(id: '154', title: 'Tonto Dikeh'),
  MangoTags(id: '155', title: 'Iyabo Ojo'),
  MangoTags(id: '156', title: 'Olu Jacobs'),
  MangoTags(id: '157', title: 'Nafisa Abdullahi'),
  MangoTags(id: '158', title: 'Jim Iyke'),
  MangoTags(id: '159', title: 'Nancy Isime'),
  MangoTags(id: '160', title: 'Alex Ekubo'),
  MangoTags(id: '161', title: 'Tekno'),
  MangoTags(id: '162', title: 'MC Galaxy'),
  MangoTags(id: '163', title: 'Runtown'),
  MangoTags(id: '164', title: 'Diamond Platnumz'),
  MangoTags(id: '165', title: 'Lil Kesh'),
  MangoTags(id: '166', title: 'Humblesmith'),
  MangoTags(id: '167', title: 'Mayorkun'),
  MangoTags(id: '168', title: 'Peruzzi'),
  MangoTags(id: '169', title: 'Dremo'),
  MangoTags(id: '170', title: 'Standup comedy'),
  MangoTags(id: '171', title: 'Sitcoms'),
  MangoTags(id: '172', title: 'Comedy skits'),
  MangoTags(id: '173', title: 'Sketch comedy'),
  MangoTags(id: '174', title: 'Dark comedy'),
  MangoTags(id: '175', title: 'Comedians'),
  MangoTags(id: '176', title: 'Basket Mouth'),
  MangoTags(id: '177', title: 'Bovi'),
  MangoTags(id: '178', title: 'Ali Baba'),
  MangoTags(id: '179', title: 'Julius Agu'),
  MangoTags(id: '180', title: 'AY'),
  MangoTags(id: '181', title: 'Akpororo'),
  MangoTags(id: '182', title: 'Broda Shaggi'),
  MangoTags(id: '183', title: 'Buchi'),
  MangoTags(id: '184', title: 'Chigul'),
  MangoTags(id: '185', title: 'Chuks D General'),
  MangoTags(id: '186', title: 'Emmanuella'),
  MangoTags(id: '187', title: 'Frank D Don'),
  MangoTags(id: '188', title: 'Helen Paul'),
  MangoTags(id: '189', title: 'I Go Dye'),
  MangoTags(id: '190', title: 'I Go Save'),
  MangoTags(id: '191', title: 'Kpokish'),
  MangoTags(id: '192', title: 'Mark Angel'),
  MangoTags(id: '193', title: 'MC Aproko'),
  MangoTags(id: '194', title: 'MC Lively'),
  MangoTags(id: '195', title: 'Mr Macaroni'),
  MangoTags(id: '196', title: 'Okey Bakassi'),
  MangoTags(id: '197', title: 'Real Warri Pikin'),
  MangoTags(id: '198', title: 'Teju Babyface'),
  MangoTags(id: '199', title: 'Taaooma'),
  MangoTags(id: '200', title: 'Twyse Ereme'),
  MangoTags(id: '201', title: 'Action'),
  MangoTags(id: '202', title: 'Animated'),
  MangoTags(id: '203', title: 'Anime'),
  MangoTags(id: '204', title: 'Nollywood'),
  MangoTags(id: '205', title: 'Bollywood'),
  MangoTags(id: '206', title: 'Comedy'),
  MangoTags(id: '207', title: 'Documentary'),
  MangoTags(id: '208', title: 'Drama'),
  MangoTags(id: '209', title: 'Fantasy'),
  MangoTags(id: '210', title: 'Horror'),
  MangoTags(id: '211', title: 'Musical theatre'),
  MangoTags(id: '212', title: 'Science fiction'),
  MangoTags(id: '213', title: 'Thriller'),
  MangoTags(id: '214', title: 'Ghallywood'),
  MangoTags(id: '215', title: 'Action & Adventure'),
  MangoTags(id: '216', title: 'Romance'),
  MangoTags(id: '217', title: 'Actors'),
  MangoTags(id: '218', title: 'Actresses'),
  MangoTags(id: '219', title: 'Movie directors'),
  MangoTags(id: '220', title: 'Film making'),
  MangoTags(id: '221', title: 'New box-office'),
  MangoTags(id: '222', title: 'Squid game'),
  MangoTags(id: '223', title: 'Coming to america'),
  MangoTags(id: '225', title: 'Sex life'),
  MangoTags(id: '226', title: 'Black widow'),
  MangoTags(id: '227', title: 'Cybersecurity'),
  MangoTags(id: '228', title: 'Data science'),
  MangoTags(id: '229', title: 'Interest of things'),
  MangoTags(id: '230', title: 'Microsoft'),
  MangoTags(id: '231', title: 'Adobe'),
  MangoTags(id: '232', title: 'Fintech'),
  MangoTags(id: '233', title: 'Video games'),
  MangoTags(id: '234', title: 'Software engineering'),
  MangoTags(id: '235', title: 'Youtube'),
  MangoTags(id: '236', title: 'Coding'),
  MangoTags(id: '237', title: 'Renewable energy'),
  MangoTags(id: '238', title: 'Women in tech'),
  MangoTags(id: '239', title: 'Smart technology'),
  MangoTags(id: '240', title: 'Google'),
  MangoTags(id: '241', title: 'Tech industry'),
  MangoTags(id: '242', title: 'Facebook'),
  MangoTags(id: '243', title: 'Twitter'),
  MangoTags(id: '244', title: 'Apple'),
  MangoTags(id: '245', title: 'Programming'),
  MangoTags(id: '246', title: 'Python'),
  MangoTags(id: '247', title: 'Html'),
  MangoTags(id: '248', title: 'Flutter'),
  MangoTags(id: '249', title: 'Visual studios'),
  MangoTags(id: '250', title: 'Data visualization'),
  MangoTags(id: '251', title: 'Artificial intelligence'),
  MangoTags(id: '252', title: 'Tech personalities'),
  MangoTags(id: '253', title: 'Richard Branson'),
  MangoTags(id: '254', title: 'Tim cook'),
  MangoTags(id: '255', title: 'Jeff Bezos'),
  MangoTags(id: '256', title: 'Elon musk'),
  MangoTags(id: '257', title: 'Mark Zuckerberg'),
  MangoTags(id: '258', title: 'Jack Ma'),
  MangoTags(id: '259', title: 'Blockchain'),
  MangoTags(id: '260', title: 'Bitcoin'),
  MangoTags(id: '261', title: 'NFT'),
  MangoTags(id: '262', title: 'Graphic design'),
  MangoTags(id: '263', title: 'Visual arts'),
  MangoTags(id: '264', title: 'Street arts'),
  MangoTags(id: '265', title: 'Painting'),
  MangoTags(id: '266', title: 'Sculpting'),
  MangoTags(id: '267', title: 'Supernatural'),
  MangoTags(id: '268', title: 'Photography'),
  MangoTags(id: '269', title: 'Drawing'),
  MangoTags(id: '270', title: 'Cartoon'),
  MangoTags(id: '271', title: 'caricature'),
  MangoTags(id: '272', title: 'Ceramics'),
  MangoTags(id: '273', title: 'Interior design'),
  MangoTags(id: '275', title: 'Pop art'),
  MangoTags(id: '276', title: 'Digital art'),
  MangoTags(id: '277', title: 'Film making'),
  MangoTags(id: '278', title: 'Illustrations'),
  MangoTags(id: '279', title: 'Graffiti Arts'),
  MangoTags(id: '280', title: 'Fine Art'),
  MangoTags(id: '281', title: 'Sketch Art'),
  MangoTags(id: '282', title: 'African Art'),
  MangoTags(id: '283', title: 'Graffiti'),
  MangoTags(id: '284', title: 'Urban Street Art'),
  MangoTags(id: '285', title: 'The Eclectic Style'),
  MangoTags(id: '286', title: 'European Art'),
  MangoTags(id: '287', title: 'Van Gogh’s'),
  MangoTags(id: '288', title: 'Art and Feminism'),
  MangoTags(id: '289', title: 'Printmaking'),
  MangoTags(id: '290', title: 'Photography'),
  MangoTags(id: '291', title: 'Modern Photography'),
  MangoTags(id: '292', title: 'War Photography'),
  MangoTags(id: '293', title: 'Secret Street Photography'),
  MangoTags(id: '294', title: 'Photography Among the Fine Arts'),
  MangoTags(id: '295', title: 'Architectural Photography'),
  MangoTags(id: '296', title: 'Photography in the Film Industry'),
  MangoTags(id: '297', title: 'Digital Technology'),
  MangoTags(id: '298', title: 'Self-Portrait'),
  MangoTags(id: '299', title: 'Selfies'),
  MangoTags(id: '300', title: 'Covid-19'),
  MangoTags(id: '301', title: 'Malaria'),
  MangoTags(id: '302', title: 'Lassa fever'),
  MangoTags(id: '303', title: 'Ebola'),
  MangoTags(id: '304', title: 'Injuries and wounds'),
  MangoTags(id: '305', title: 'Mental health and behavior'),
  MangoTags(id: '306', title: 'Drug abuse'),
  MangoTags(id: '307', title: 'Pregnancy and reproduction'),
  MangoTags(id: '308', title: 'Substance abuse problems'),
  MangoTags(id: '309', title: 'Transplantation and donation'),
  MangoTags(id: '310', title: 'Children health care'),
  MangoTags(id: '311', title: 'Older adult’s health'),
  MangoTags(id: '312', title: 'Women’s health'),
  MangoTags(id: '313', title: 'Disasters'),
  MangoTags(id: '314', title: 'Fitness and exercise'),
  MangoTags(id: '315', title: 'Food and nutrition'),
  MangoTags(id: '316', title: 'Health system'),
  MangoTags(id: '317', title: 'Personal health issues'),
  MangoTags(id: '318', title: 'Safety issues'),
  MangoTags(id: '319', title: 'Sexual health'),
  MangoTags(id: '320', title: 'Wellness and lifestyle'),
  MangoTags(id: '321', title: 'Omicron'),
  MangoTags(id: '322', title: 'Doctors'),
  MangoTags(id: '323', title: 'Action'),
  MangoTags(id: '324', title: 'Board games'),
  MangoTags(id: '325', title: 'Card'),
  MangoTags(id: '326', title: 'Casino'),
  MangoTags(id: '327', title: 'First-person shooter'),
  MangoTags(id: '328', title: 'Gambling'),
  MangoTags(id: '329', title: 'Multiplayer'),
  MangoTags(id: '330', title: 'Online games'),
  MangoTags(id: '331', title: 'Online poker'),
  MangoTags(id: '332', title: 'Puzzle video games'),
  MangoTags(id: '333', title: 'Racing'),
  MangoTags(id: '334', title: 'Role-playing'),
  MangoTags(id: '335', title: 'Shooter'),
  MangoTags(id: '336', title: 'Simulation'),
  MangoTags(id: '337', title: 'Sports'),
  MangoTags(id: '338', title: 'Strategy games'),
  MangoTags(id: '339', title: 'Video games'),
  MangoTags(id: '340', title: 'Word games'),
  MangoTags(id: '341', title: 'Playstation'),
  MangoTags(id: '342', title: 'SEGA'),
  MangoTags(id: '343', title: 'FIFA'),
  MangoTags(id: '344', title: 'X-BOX'),
  MangoTags(id: '345', title: 'GTA'),
  MangoTags(id: '346', title: 'Matter'),
  MangoTags(id: '347', title: 'Energy'),
  MangoTags(id: '348', title: 'Electrochemistry'),
  MangoTags(id: '349', title: 'Units and Measurement'),
  MangoTags(id: '350', title: 'Thermochemistry'),
  MangoTags(id: '351', title: 'Chemical Bonding'),
  MangoTags(id: '352', title: 'Environmental Chemistry'),
  MangoTags(id: '353', title: 'Physical organic'),
  MangoTags(id: '354', title: 'Radiochemistry'),
  MangoTags(id: '355', title: 'Forensic Chemistry'),
  MangoTags(id: '356', title: 'Geography'),
  MangoTags(id: '357', title: 'Human Geography'),
  MangoTags(id: '358', title: 'Physical geography'),
  MangoTags(id: '359', title: 'Economic geography'),
  MangoTags(id: '362', title: 'Climatology'),
  MangoTags(id: '363', title: 'Urban Geography'),
  MangoTags(id: '362', title: 'Oceanography'),
  MangoTags(id: '365', title: 'water resources'),
  MangoTags(id: '366', title: 'Social geography'),
  MangoTags(id: '367', title: 'Biology'),
  MangoTags(id: '368', title: 'Ecology'),
  MangoTags(id: '369', title: 'Genetics'),
  MangoTags(id: '370', title: 'Zoology'),
  MangoTags(id: '371', title: 'Botany'),
  MangoTags(id: '372', title: 'Microbiology'),
  MangoTags(id: '373', title: 'Biochemistry'),
  MangoTags(id: '374', title: 'Anatomy'),
  MangoTags(id: '375', title: 'Marine Biology'),
  MangoTags(id: '376', title: 'Evolution'),
  MangoTags(id: '377', title: 'Bacteriology'),
  MangoTags(id: '378', title: 'Virology'),
  MangoTags(id: '379', title: 'Cooking'),
  MangoTags(id: '380', title: 'Fashion'),
  MangoTags(id: '381', title: 'Home improvement'),
  MangoTags(id: '382', title: 'Family'),
  MangoTags(id: '383', title: 'Adult community'),
  MangoTags(id: '384', title: 'Resort centers'),
  MangoTags(id: '385', title: 'Food'),
  MangoTags(id: '387', title: 'Couples'),
  MangoTags(id: '388', title: 'Leisure behaviors'),
  MangoTags(id: '389', title: 'Dating'),
  MangoTags(id: '390', title: 'Pets'),
  MangoTags(id: '391', title: 'Parenting'),
  MangoTags(id: '392', title: 'Baking'),
  MangoTags(id: '393', title: 'Bread making'),
  MangoTags(id: '394', title: 'Relationships'),
  MangoTags(id: '395', title: 'Friendships'),
  MangoTags(id: '397', title: 'Dancing'),
  MangoTags(id: '398', title: 'Singing'),
  MangoTags(id: '399', title: 'Personal hygiene'),
  MangoTags(id: '400', title: 'Environmental hygiene'),
  MangoTags(id: '401', title: 'Fitness'),
  MangoTags(id: '402', title: 'Health'),
  MangoTags(id: '403', title: 'City culture'),
  MangoTags(id: '404', title: 'Diversity'),
  MangoTags(id: '405', title: 'Cosmology'),
  MangoTags(id: '406', title: 'Astronomy'),
  MangoTags(id: '407', title: 'NASA'),
  MangoTags(id: '408', title: 'SPACE X'),
  MangoTags(id: '409', title: 'Solar System'),
  MangoTags(id: '410', title: 'Stars and the galaxy'),
  MangoTags(id: '411', title: 'UFO'),
  MangoTags(id: '412', title: 'Extragalactic'),
  MangoTags(id: '413', title: 'Sun'),
  MangoTags(id: '414', title: 'Planets'),
  MangoTags(id: '415', title: 'Moon'),
  MangoTags(id: '416', title: 'Jupiter'),
  MangoTags(id: '417', title: 'Mercury'),
  MangoTags(id: '418', title: 'Mars'),
  MangoTags(id: '419', title: 'Accounting'),
  MangoTags(id: '420', title: 'Financial services'),
  MangoTags(id: '421', title: 'Nonprofits'),
  MangoTags(id: '422', title: 'Business personalities'),
  MangoTags(id: '423', title: 'Startups'),
  MangoTags(id: '424', title: 'Telecom'),
  MangoTags(id: '425', title: 'Insurance'),
  MangoTags(id: '426', title: 'SEO'),
  MangoTags(id: '427', title: 'Marketing'),
  MangoTags(id: '428', title: 'Product management'),
  MangoTags(id: '429', title: 'Digital marketing'),
  MangoTags(id: '430', title: 'Stock exchange market'),
  MangoTags(id: '431', title: 'Nigerian stock exchange'),
  MangoTags(id: '432', title: 'Forex'),
  MangoTags(id: '433', title: 'Blockchain'),
  MangoTags(id: '434', title: 'Bitcoin'),
  MangoTags(id: '435', title: 'Etherum'),
  MangoTags(id: '436', title: 'Litherum'),
  MangoTags(id: '437', title: 'NFT'),
  MangoTags(id: '438', title: 'Cryptocurrency'),
  MangoTags(id: '439', title: 'Sales and promotions'),
  MangoTags(id: '440', title: 'Business news'),
  MangoTags(id: '441', title: 'Business policies'),
  MangoTags(id: '442', title: 'Marketing strategies'),
  MangoTags(id: '443', title: 'World business'),
  MangoTags(id: '444', title: 'Nigerian business'),
  MangoTags(id: '445', title: 'Opinions'),
  MangoTags(id: '446', title: 'Columnist'),
  MangoTags(id: '447', title: 'Letters'),
  MangoTags(id: '448', title: 'Business education'),
  MangoTags(id: '449', title: 'Entrepreneurship'),
  MangoTags(id: '450', title: 'Business books'),
  MangoTags(id: '451', title: 'Investments'),
  MangoTags(id: '452', title: 'Pension'),
  MangoTags(id: '453', title: 'Tax'),
  MangoTags(id: '454', title: 'Banking & savings'),
  MangoTags(id: '455', title: 'Marketing & sales'),
  MangoTags(id: '456', title: 'Tourist destinations'),
  MangoTags(id: '457', title: 'Travel guides'),
  MangoTags(id: '458', title: 'Travel updates'),
  MangoTags(id: '459', title: 'Travel stories'),
  MangoTags(id: '460', title: 'Aviation'),
  MangoTags(id: '461', title: 'Business travel'),
  MangoTags(id: '462', title: 'National parks'),
  MangoTags(id: '463', title: 'Adventure travel'),
  MangoTags(id: '464', title: 'Luxury travels'),
  MangoTags(id: '465', title: 'Cruise travel'),
  MangoTags(id: '466', title: 'Air travel'),
  MangoTags(id: '467', title: 'Travel bloggers'),
  MangoTags(id: '468', title: 'Hotels'),
  MangoTags(id: '469', title: 'African travel'),
  MangoTags(id: '470', title: 'Road trips'),
  MangoTags(id: '471', title: 'Rock climbing'),
  MangoTags(id: '472', title: 'Camping'),
  MangoTags(id: '473', title: 'Railway travels'),
  MangoTags(id: '474', title: 'Space travel'),
  MangoTags(id: '475', title: 'Cultures'),
  MangoTags(id: '476', title: 'Languages'),
  MangoTags(id: '477', title: 'Festivals'),
  MangoTags(id: '478', title: 'Weather reports'),
  MangoTags(id: '479', title: 'Road transportation'),
  MangoTags(id: '480', title: 'World news'),
  MangoTags(id: '481', title: 'Covid-19'),
  MangoTags(id: '482', title: 'World politics'),
  MangoTags(id: '483', title: '2023 elections'),
  MangoTags(id: '484', title: 'Weather'),
  MangoTags(id: '485', title: 'Current affairs'),
  MangoTags(id: '486', title: 'Hard news'),
  MangoTags(id: '487', title: 'Breaking news'),
  MangoTags(id: '488', title: 'Featured news'),
  MangoTags(id: '489', title: 'World economy'),
  MangoTags(id: '490', title: 'Political discussions'),
  MangoTags(id: '491', title: 'Crime news'),
  MangoTags(id: '492', title: 'Investigative journalism'),
  MangoTags(id: '493', title: 'Nigeria politics'),
  MangoTags(id: '494', title: 'Nigeria economy'),
  MangoTags(id: '495', title: 'Columns'),
  MangoTags(id: '496', title: 'Editorials'),
  MangoTags(id: '497', title: 'Developmental news'),
  MangoTags(id: '498', title: 'Sport news'),
  MangoTags(id: '499', title: 'Local news'),
  MangoTags(id: '500', title: 'TVC'),
  MangoTags(id: '501', title: 'Channels tv'),
  MangoTags(id: '502', title: 'NTA'),
  MangoTags(id: '503', title: 'BBC'),
  MangoTags(id: '504', title: 'CNN'),
  MangoTags(id: '505', title: 'Aljazera'),
  MangoTags(id: '506', title: 'Traditional African practices'),
  MangoTags(id: '507', title: 'Christianity'),
  MangoTags(id: '508', title: 'Islam'),
  MangoTags(id: '509', title: 'Judaism'),
  MangoTags(id: '510', title: 'Buddhism'),
  MangoTags(id: '511', title: 'Hinduism'),
  MangoTags(id: '512', title: 'Atheism'),
  MangoTags(id: '513', title: 'Catholicism'),
  MangoTags(id: '514', title: 'Rastafarianism'),
  MangoTags(id: '515', title: 'Climate change'),
  MangoTags(id: '516', title: 'Energy'),
  MangoTags(id: '517', title: 'Water'),
  MangoTags(id: '518', title: 'Biodiversity and land use'),
  MangoTags(id: '519', title: 'Chemical and toxic waste'),
  MangoTags(id: '520', title: 'Air pollution'),
  MangoTags(id: '521', title: 'Waste management'),
  MangoTags(id: '522', title: 'Ozone layer depletion'),
  MangoTags(id: '523', title: 'Water pollution'),
  MangoTags(id: '524', title: 'Ecosystem'),
  MangoTags(id: '525', title: 'Agriculture'),
  MangoTags(id: '526', title: 'Environmental economics'),
  MangoTags(id: '527', title: 'Soil'),
  MangoTags(id: '528', title: 'Natural resources'),
  MangoTags(id: '529', title: 'Soil quality'),
  MangoTags(id: '530', title: 'Pollution prevention'),
  MangoTags(id: '531', title: 'Marine conservation'),
  MangoTags(id: '532', title: 'Drinking water'),
  MangoTags(id: '533', title: 'Noise pollution'),
  MangoTags(id: '534', title: 'Occupational safety and health'),
  MangoTags(id: '535', title: 'Environmental sanitation'),
  MangoTags(id: '536', title: 'Archaeology'),
  MangoTags(id: '537', title: 'Alternative fuels'),
  MangoTags(id: '538', title: 'Ecotourism'),
  MangoTags(id: '539', title: 'Energy conservation'),
  MangoTags(id: '540', title: 'Sustainable technology'),
  MangoTags(id: '541', title: 'Waste reduction'),
  MangoTags(id: '542', title: 'Water conservation'),
  MangoTags(id: '543', title: 'Sustainable agriculture'),
  MangoTags(id: '544', title: 'Wildlife conservation'),
  MangoTags(id: '545', title: 'Christmas'),
  MangoTags(id: '546', title: 'New year'),
  MangoTags(id: '547', title: 'Easters'),
  MangoTags(id: '548', title: 'Ramadan'),
  MangoTags(id: '549', title: 'Eid al-fitr'),
  MangoTags(id: '550', title: 'Yam festivals'),
  MangoTags(id: '551', title: 'Calabar festivals'),
  MangoTags(id: '552', title: 'Osun festival'),
  MangoTags(id: '553', title: 'Valentine'),
  MangoTags(id: '554', title: 'Public holidays'),
  MangoTags(id: '555', title: 'National holidays'),
  MangoTags(id: '556', title: 'International holidays'),
  MangoTags(id: '557', title: 'World history'),
  MangoTags(id: '558', title: 'Origin of man'),
  MangoTags(id: '559', title: 'Ancient history'),
  MangoTags(id: '560', title: 'World war I'),
  MangoTags(id: '561', title: 'World war II'),
  MangoTags(id: '562', title: 'Slavery'),
  MangoTags(id: '563', title: 'African-American history'),
  MangoTags(id: '564', title: 'Ancient Egypt'),
  MangoTags(id: '565', title: 'Modern history'),
  MangoTags(id: '566', title: 'Art history'),
  MangoTags(id: '567', title: 'Cold war'),
  MangoTags(id: '568', title: 'Civil and political rights'),
  MangoTags(id: '569', title: 'Women’s history'),
  MangoTags(id: '570', title: 'Economic history'),
  MangoTags(id: '571', title: 'Wars'),
  MangoTags(id: '572', title: 'Culture'),
  MangoTags(id: '573', title: 'Nigeria political history'),
  MangoTags(id: '574', title: 'Vintage fashion'),
  MangoTags(id: '575', title: 'Casual men fashion'),
  MangoTags(id: '576', title: 'Casual women fashion'),
  MangoTags(id: '577', title: 'Sexy fashion styles'),
  MangoTags(id: '578', title: 'Models'),
  MangoTags(id: '579', title: 'Stylists'),
  MangoTags(id: '580', title: 'Fashion brands'),
  MangoTags(id: '581', title: 'Makeup'),
  MangoTags(id: '582', title: 'Cosmetics'),
  MangoTags(id: '583', title: 'Urban fashion'),
  MangoTags(id: '584', title: 'Street fashion'),
  MangoTags(id: '585', title: 'Exotic fashion style'),
  MangoTags(id: '586', title: 'Fashion trends'),
  MangoTags(id: '587', title: 'Fashion News'),
  MangoTags(id: '588', title: 'Best trends'),
  MangoTags(id: '589', title: 'African fashion'),
  MangoTags(id: '590', title: 'Native styles for men'),
  MangoTags(id: '591', title: 'Women’s style'),
  MangoTags(id: '592', title: 'Men’s wear'),
  MangoTags(id: '593', title: 'Hair care'),
  MangoTags(id: '594', title: 'Fashion columns'),
  MangoTags(id: '595', title: 'Fashion police'),
  MangoTags(id: '596', title: 'Sneakers'),
  MangoTags(id: '597', title: 'Jackets'),
  MangoTags(id: '598', title: 'Blouse'),
  MangoTags(id: '599', title: 'Shoes'),
  MangoTags(id: '600', title: 'Watches'),
  MangoTags(id: '601', title: 'Jewelries'),
  MangoTags(id: '602', title: 'Wardrobe management'),
  MangoTags(id: '603', title: 'Fashion shows'),
  MangoTags(id: '604', title: 'Fashion industry'),
  MangoTags(id: '605', title: 'Fashion entrepreneurs'),
  MangoTags(id: '606', title: 'Gist and gossips'),
  MangoTags(id: '607', title: 'Red carpet events'),
  MangoTags(id: '608', title: 'Fashion police'),
  MangoTags(id: '609', title: 'Billboard'),
  MangoTags(id: '610', title: 'Grammy'),
  MangoTags(id: '611', title: 'Mtv base'),
  MangoTags(id: '612', title: 'Concerts'),
  MangoTags(id: '613', title: 'Song release'),
  MangoTags(id: '614', title: 'Albums'),
  MangoTags(id: '615', title: 'Playlists'),
  MangoTags(id: '616', title: 'Celebrities sayings'),
  MangoTags(id: '617', title: 'Partying'),
  MangoTags(id: '618', title: 'Clubbing'),
  MangoTags(id: '619', title: 'Wedding'),
];

final List<MangoTags> limitedTags = [
  MangoTags(id: '1', title: "Novels"),
  MangoTags(id: '2', title: 'Short stories'),
  MangoTags(id: '3', title: 'Creative essay'),
  MangoTags(id: '4', title: 'Poetry'),
  MangoTags(id: '5', title: 'Copywriting'),
  MangoTags(id: '6', title: 'Feature stories'),
  MangoTags(id: '7', title: 'Prose'),
  MangoTags(id: '8', title: 'Drama'),
  MangoTags(id: '9', title: 'Non-fiction'),
  MangoTags(id: '10', title: 'Adventure'),
  MangoTags(id: '11', title: 'Fairy tales'),
  MangoTags(id: '12', title: 'Sci-fi'),
  MangoTags(id: '13', title: 'Fantasy'),
  MangoTags(id: '14', title: 'Folklore'),
  MangoTags(id: '15', title: 'Craft and hobbies'),
];

final List<MangoTags> hobbies = [
  MangoTags(id: '1', title: "Hiking"),
  MangoTags(id: '2', title: 'Backpacking'),
  MangoTags(id: '3', title: 'Camping'),
  MangoTags(id: '4', title: 'Poetry'),
  MangoTags(id: '5', title: 'Hunting'),
  MangoTags(id: '6', title: 'Fishing'),
  MangoTags(id: '7', title: 'Archery'),
  MangoTags(id: '8', title: 'Canoeing'),
  MangoTags(id: '9', title: 'Kayaking'),
  MangoTags(id: '10', title: 'Running'),
  MangoTags(id: '11', title: 'Geocaching'),
  MangoTags(id: '12', title: 'Growing Vegetables'),
  MangoTags(id: '13', title: 'Composting'),
  MangoTags(id: '14', title: 'Metal Detecting'),
  MangoTags(id: '15', title: 'Bird Watching'),
  MangoTags(id: '16', title: 'Beekeeping'),
  MangoTags(id: '17', title: 'LARPing'),
  MangoTags(id: '18', title: 'Parkour'),
  MangoTags(id: '19', title: 'Astronomy'),
  MangoTags(id: '20', title: 'Meteorology'),
  MangoTags(id: '21', title: 'Kite Flying'),
  MangoTags(id: '22', title: 'Sand Castle Making'),
  MangoTags(id: '23', title: 'Hobby Horsing'),
  MangoTags(id: '24', title: 'Antiquing'),
  MangoTags(id: '25', title: 'Coin Collecting'),
  MangoTags(id: '26', title: 'Stamp Collecting'),
  MangoTags(id: '27', title: 'Vintage Clothing Collecting'),
  MangoTags(id: '28', title: 'Classic Car Collecting'),
  MangoTags(id: '29', title: 'Antique Book and Manuscript Collecting'),
  MangoTags(id: '30', title: 'Art Collecting'),
  MangoTags(id: '31', title: 'Shell and Sea Glass Collecting'),
  MangoTags(id: '32', title: 'Leaf Collecting and Pressing'),
  MangoTags(id: '33', title: 'Record Collecting'),
  MangoTags(id: '34', title: 'Postcard Collecting'),
  MangoTags(id: '35', title: 'Shoe Collecting'),
  MangoTags(id: '36', title: 'Toy Collecting'),
  MangoTags(id: '37', title: 'Memorabilia Collecting '),
  MangoTags(id: '38', title: 'Sports Memorabilia Collecting'),
  MangoTags(id: '39', title: 'Rock Tumbling'),
  MangoTags(id: '40', title: 'Cooking'),
  MangoTags(id: '41', title: 'Baking'),
  MangoTags(id: '42', title: 'Gingerbread House Making'),
  MangoTags(id: '43', title: 'Home Brewing'),
  MangoTags(id: '44', title: 'Wine Making'),
  MangoTags(id: '45', title: 'Mixology'),
  MangoTags(id: '46', title: 'Bread Making'),
  MangoTags(id: '47', title: 'Cheese Making'),
  MangoTags(id: '48', title: 'Sewing'),
  MangoTags(id: '49', title: 'Painting'),
  MangoTags(id: '50', title: 'Drawing'),
  MangoTags(id: '51', title: 'Origami'),
  MangoTags(id: '52', title: 'Photography'),
  MangoTags(id: '53', title: 'Scrapbooking'),
  MangoTags(id: '54', title: 'Calligraphy'),
  MangoTags(id: '55', title: 'Quilting'),
  MangoTags(id: '56', title: 'Crocheting'),
  MangoTags(id: '57', title: 'Knitting'),
  MangoTags(id: '58', title: 'Embroidery'),
  MangoTags(id: '59', title: 'Carpet and Tapestry Weaving'),
  MangoTags(id: '60', title: 'Designing and Making Clothes'),
  MangoTags(id: '61', title: 'Jewelry Making'),
  MangoTags(id: '62', title: 'Pottery'),
  MangoTags(id: '63', title: 'Metal Working'),
  MangoTags(id: '64', title: 'Wood Carving'),
  MangoTags(id: '65', title: 'Welding'),
  MangoTags(id: '66', title: 'Leather Tooling'),
  MangoTags(id: '67', title: 'Cobbling'),
  MangoTags(id: '68', title: 'Model Railroads'),
  MangoTags(id: '69', title: 'Furniture Building'),
  MangoTags(id: '70', title: 'Home Improvement'),
  MangoTags(id: '71', title: 'Model Building'),
  MangoTags(id: '72', title: 'LEGO'),
  MangoTags(id: '73', title: 'Trivia'),
  MangoTags(id: '74', title: 'Video Games'),
  MangoTags(id: '75', title: 'Board Games'),
  MangoTags(id: '76', title: 'Card Games'),
  MangoTags(id: '78', title: 'Chess'),
  MangoTags(id: '79', title: 'Puzzles'),
  MangoTags(id: '80', title: 'Jigsaw'),
  MangoTags(id: '81', title: 'Crosswords'),
  MangoTags(id: '82', title: 'Juggling'),
  MangoTags(id: '83', title: 'Table Tennis'),
  MangoTags(id: '84', title: 'Billiards'),
  MangoTags(id: '85', title: 'Genealogy'),
  MangoTags(id: '86', title: 'Language Learning'),
  MangoTags(id: '87', title: 'Journaling'),
  MangoTags(id: '88', title: 'Creative Writing'),
  MangoTags(id: '89', title: 'Book Club'),
  MangoTags(id: '90', title: 'Wikipedia Editing'),
  MangoTags(id: '91', title: 'Volunteering for a Historical Society'),
  MangoTags(id: '92', title: 'Playing an Instrument'),
  MangoTags(id: '93', title: 'Podcast Hosting'),
  MangoTags(id: '94', title: 'Amateur Radio'),
  MangoTags(id: '95', title: 'Thrifting'),
  MangoTags(id: '96', title: 'Makeup'),
  MangoTags(id: '97', title: 'Dancing'),
  MangoTags(id: '98', title: 'Hula Hooping'),
  MangoTags(id: '99', title: 'Aquarium Keeping'),
  MangoTags(id: '100', title: 'Computer Programming'),
  MangoTags(id: '101', title: 'Working on Cars'),
  MangoTags(id: '102', title: 'Travel'),
  MangoTags(id: '103', title: 'Cosplaying'),
  MangoTags(id: '104', title: 'Survivalist Prepping'),
  MangoTags(id: '105', title: 'Scuba Diving'),
  MangoTags(id: '106', title: 'Mountain Biking'),
  MangoTags(id: '107', title: 'Hiking'),
  MangoTags(id: '108', title: 'Coffee Roasting'),
  MangoTags(id: '109', title: 'Adult Coloring'),
  MangoTags(id: '110', title: 'Frying Dodo'),
];

final List<MangoTags> hobbiesLimited = [
  MangoTags(id: '2', title: 'Backpacking'),
  MangoTags(id: '3', title: 'Camping'),
  MangoTags(id: '4', title: 'Poetry'),
  MangoTags(id: '5', title: 'Hunting'),
  MangoTags(id: '6', title: 'Fishing'),
  MangoTags(id: '7', title: 'Archery'),
  MangoTags(id: '26', title: 'Stamp Collecting'),
  MangoTags(id: '27', title: 'Vintage Clothing Collecting'),
  MangoTags(id: '29', title: 'Antique Book and Manuscript Collecting'),
  MangoTags(id: '30', title: 'Art Collecting'),
  MangoTags(id: '95', title: 'Thrifting'),
  MangoTags(id: '96', title: 'Makeup'),
  MangoTags(id: '97', title: 'Dancing'),
  MangoTags(id: '98', title: 'Hula Hooping'),
  MangoTags(id: '99', title: 'Aquarium Keeping'),
  MangoTags(id: '100', title: 'Computer Programming'),
  MangoTags(id: '101', title: 'Working on Cars'),
  MangoTags(id: '102', title: 'Travel'),
  MangoTags(id: '103', title: 'Dancing'),
];







