class InterestList {
  static var books = [
    "Novels",
    "Short stories",
    "Creative essay",
    "Poetry",
    "Copywriting",
    "Feature stories",
    "Prose",
    "Drama",
    "Fiction",
    "Non-fiction",
    "Adventure",
    "Fairy tales",
    "Sci-fi",
    "Fantasy",
    "Folklore",
    "Craft and hobbies",
    "Horror",
    "Science and technology",
    "Religion",
    "News writing",
    "Content writers"
  ];

  static var music = [
    'Hiphop',
    'Dance',
    'Soul',
    'Jazz',
    'R&B',
    'EDM',
    'Grime',
    'Apala',
    'Sakara',
    'House',
    'Electro',
    'Rock',
    'Pop',
    'Afrobeats',
    'Afrohouse',
    'Afrosoul',
    'Afro-pop',
    'Trap',
    'Blues',
    'Raggae',
    'Techno',
    'Instrumentals',
    'Indie',
    'Fuji',
    'Juju',
    'Highlife',
    'Gospel',
    'Lullaby'
  ];

  static var philosophy = [
    'Ethnics',
    'metaphysics',
    'Aesthetics',
    'Logic',
    'Phenomenology',
    'Philosophy of religion',
    'Charles Dawin',
    'Aristotle',
    'Plato',
    'Socrates',
    'Pythagoras',
    'Humanism',
    'Philosophy and science',
    'Philosophy and technology',
    'Social sciences',
    'Pure science',
    'Applied science',
  ];

  static var psychology = [
    'Behavior',
    'Child improvement',
    'Depression',
    'Ageing',
    'Anxiety',
    'Applied Pyschology',
    'Autism',
    'Sleep',
    'Decision-making',
  ];

  static var liveEvents = [
    'Ballet',
    'Bars',
    'Concerts',
    'Dancehalls',
    'Music festivals',
    'Nightclubs',
    'Parties',
    'Plays',
    'Theatre',
  ];

  static var sport = [
    'Physical sports',
    'Football',
    'Basketball',
    'Tennis',
    'Table tennis',
    'Lawn tennis',
    'Volleyball',
    'Golf',
    'Hockey',
    'Marathon',
    'Formula 1',
    'Track and field sports',
    'Indoor sports',
    'Baseball',
    'Cricket',
    'Boxing',
    'Wrestling',
    'Athletics',
    'Cycling',
    'Badminton',
    'Recreational',
    'Yoga',
    'Swimming',
    'Running',
    'Beach racing',
    'Bike',
    'Skating',
    'Surfing',
    'Exercises & workout',
    'Camping',
    'Surfing',
    'Bet',
    'Bet9ja',
    'Nairabet',
    'KingsBet',
    'SportyBet',
    '1x Bet',
    'Virtual betting',
  ];

  static var celebrities = [
    'Davido',
    'Wizkid',
    'Burna boy',
    'Don jazzy',
    'Olamide',
    'Phyno',
    'Tiwa savage',
    'Tems',
    'Niniola',
    'Dbanj',
    'Tuface',
    'Mercy Johnson',
    'Funke Akindele',
    'Desmond Eliot',
    'Ramsey Noah',
    'Aki & Pawpaw',
    'Ruger',
    'Rema',
    'Ayra Starr',
    'Buju',
    'Bobby Shmurda',
    'Seyi Shay',
    'Chidinma Ekile',
    'Naira Marley',
    'Destiny Etiko',
    'Zubby Michael',
    'Pere',
    'Tonto Dikeh',
    'Iyabo Ojo',
    'Olu Jacobs',
    'Nafisa Abdullahi',
    'Jim Iyke',
    'Nancy Isime',
    'Alex Ekubo',
    'Tekno',
    'MC Galaxy',
    'Runtown',
    'Diamond Platnumz',
    'Lil Kesh',
    'Humblesmith',
    'Mayorkun',
    'Peruzzi',
    'Dremo',
  ];

  static var comedy = [
    'Standup comedy',
    'Sitcoms',
    'Comedy skits',
    'Sketch comedy',
    'Dark comedy',
    'Comedians',
    'Basket Mouth',
    'Bovi',
    'Ali Baba',
    'Julius Agu',
    'AY',
    'Akpororo',
    'Broda Shaggi',
    'Buchi',
    'Chigul',
    'Chuks D General',
    'Emmanuella',
    'Frank D Don',
    'Helen Paul',
    'I Go Dye',
    'I Go Save',
    'Kpokish',
    'Mark Angel',
    'MC Aproko',
    'MC Lively',
    'Mr Macaroni',
    'Okey Bakassi',
    'Real Warri Pikin,'
        'Teju Babyface',
    'Taaooma',
    'Twyse Ereme',
  ];

  static var movies = [
    'Action',
    'Animated',
    'Anime',
    'Nollywood',
    'Bollywood',
    'Comedy',
    'Documentary',
    'Drama',
    'Fantasy',
    'Horror',
    'Musical theatre',
    'Science fiction',
    'Thriller',
    'Ghallywood',
    'Action & Adventure',
    'Romance',
    'Actors',
    'Actresses',
    'Movie directors',
    'Film making',
    'New box-office',
    'Squid game',
    'Coming to america',
    'Sex life',
    'Black widow',
  ];

  static var innovationsAndTech = [
    'Cybersecurity',
    'Data science',
    'Interest of things',
    'Microsoft',
    'Adobe',
    'Fintech',
    'Video games',
    'Software engineering',
    'Youtube',
    'Coding',
    'Renewable energy',
    'Women in tech',
    'Smart technology',
    'Google',
    'Tech industry',
    'Facebook',
    'Twitter',
    'Apple',
    'Programming',
    'Python',
    'Html',
    'Flutter',
    'Visual studios',
    'Data visualization',
    'Artificial intelligence',
    'Tech personalities',
    'Richard Branson',
    'Tim cook',
    'Jeff Bezos',
    'Elon musk',
    'Mark Zuckerberg',
    'Jack Ma',
    'Blockchain',
    'Bitcoin',
    'NFT'
  ];

  static var artAndDesign = [
    'Graphic design',
    'Visual arts',
    'Street arts',
    'Painting',
    'Sculpting',
    'Supernatural',
    'Photography',
    'Drawing',
    'Cartoon',
    'caricature',
    'Ceramics',
    'Interior design',
    'Pop art',
    'Digital art',
    'Film making',
    'Illustrations',
    'Graffiti Arts',
    'Fine Art',
    'Sketch Art',
    'African Art',
    'Graffiti',
    'Urban Street Art',
    'The Eclectic Style',
    'European Art',
    'Van Gogh’s',
    'Art and Feminism',
    'Printmaking',
    'Photography',
    'Modern Photography',
    'War Photography',
    'Secret Street Photography',
    'Photography Among the Fine Arts',
    'Architectural Photography',
    'Photography in the Film Industry',
    'Digital Technology',
    'Self-Portrait',
    'Selfies',
  ];

  static var health = [
    'Covid-19',
    'Malaria',
    'Lassa fever',
    'Ebola',
    'Injuries and wounds',
    'Mental health and behavior',
    'Drug abuse',
    'Pregnancy and reproduction',
    'Substance abuse problems',
    'Transplantation and donation',
    'Children health care',
    'Older adult’s health',
    'Women’s health',
    'Disasters',
    'Fitness and exercise',
    'Food and nutrition',
    'Health system',
    'Personal health issues',
    'Safety issues',
    'Sexual health',
    'Wellness and lifestyle',
    'Omicron',
    'Doctors'
  ];

  static var games = [
    'Action',
    'Board games',
    'Card',
    'Casino',
    'First-person shooter',
    'Gambling',
    'Multiplayer',
    'Online games',
    'Online poker',
    'Puzzle video games',
    'Racing',
    'Role-playing',
    'Shooter',
    'Simulation',
    'Sports',
    'Strategy games',
    'Video games',
    'Word games',
    'Playstation',
    'SEGA',
    'FIFA',
    'X-BOX',
    'GTA'
  ];

  static var science = [
    'Matter',
    'Energy',
    'Electrochemistry',
    'Units and Measurement',
    'Thermochemistry',
    'Chemical Bonding',
    'Environmental Chemistry',
    'Physical organic',
    'Radiochemistry',
    'Forensic Chemistry',
    'Geography',
    'Human Geography',
    'Physical geography',
    'Economic geography',
    'Climatology',
    'Urban Geography',
    'Oceanography',
    'water resources',
    'Social geography',
    'Biology',
    'Ecology',
    'Genetics',
    'Zoology',
    'Botany',
    'Microbiology',
    'Biochemistry',
    'Anatomy',
    'Marine Biology',
    'Evolution',
    'Bacteriology',
    'Virology',
  ];

  static var lifestyle = [
    'Cooking',
    'Fashion',
    'Home improvement',
    'Family',
    'Adult community',
    'Resort centers',
    'Food',
    'Couples',
    'Leisure behaviors',
    'Dating',
    'Pets',
    'Parenting',
    'Baking',
    'Bread making',
    'Relationships',
    'Friendships',
    'Dancing',
    'Singing',
    'Personal hygiene',
    'Environmental hygiene',
    'Fitness',
    'Health',
    'City culture',
    'Diversity'
  ];

  static var space = [
    'Cosmology',
    'Astronomy',
    'NASA',
    'SPACE X',
    'Solar System',
    'Stars and the galaxy',
    'UFO',
    'Extragalactic',
    'Sun',
    'Planets',
    'Moon',
    'Jupiter',
    'Mercury',
    'Mars',
  ];

  static var business = [
    'Accounting',
    'Financial services',
    'Nonprofits',
    'Business personalities',
    'Startups',
    'Telecom',
    'Insurance',
    'SEO',
    'Marketing',
    'Product management',
    'Digital marketing',
    'Stock exchange market',
    'Nigerian stock exchange',
    'Forex',
    'Blockchain',
    'Bitcoin',
    'Etherum',
    'Litherum',
    'NFT',
    'Cryptocurrency',
    'Sales and promotions',
    'Business news',
    'Business policies',
    'Marketing strategies',
    'World business',
    'Nigerian business',
    'Opinions',
    'Columnist',
    'Letters',
    'Business education',
    'Entrepreneurship',
    'Business books',
    'Investments',
    'Pension',
    'Tax',
    'Banking & savings',
    'Marketing & sales'
  ];

  static var travel = [
    'Tourist destinations',
    'Travel guides',
    'Travel updates',
    'Travel stories',
    'Aviation',
    'Business travel',
    'National parks',
    'Adventure travel',
    'Luxury travels',
    'Cruise travel',
    'Air travel',
    'Travel bloggers',
    'Hotels',
    'African travel',
    'Road trips',
    'Rock climbing',
    'Camping',
    'Railway travels',
    'Space travel',
    'Cultures',
    'Languages',
    'Festivals',
    'Weather reports',
    'Road transportation'
  ];

  static var news = [
    'World news',
    'Covid-19',
    'World politics',
    '2023 elections',
    'Weather',
    'Current affairs',
    'Hard news',
    'Breaking news',
    'Featured news',
    'World economy',
    'Political discussions',
    'Crime news',
    'Investigative journalism',
    'Nigeria politics',
    'Nigeria economy',
    'Columns',
    'Editorials',
    'Developmental news',
    'Sport news',
    'Local news',
    'TVC',
    'Channels tv',
    'NTA',
    'BBC',
    'CNN',
    'Aljazera'
  ];

  static var beliefs = [
    'Traditional African practices',
    'Christianity',
    'Islam',
    'Judaism',
    'Buddhism',
    'Hinduism',
    'Atheism',
    'Catholicism',
    'Rastafarianism'
  ];

  static var eco = [
    'Climate change',
    'Energy',
    'Water',
    'Biodiversity and land use',
    'Chemical and toxic waste',
    'Air pollution',
    'Waste management',
    'Ozone layer depletion',
    'Water pollution',
    'Ecosystem',
    'Agriculture',
    'Environmental economics',
    'Soil',
    'Natural resources',
    'Soil quality',
    'Pollution prevention',
    'Marine conservation',
    'Drinking water',
    'Noise pollution',
    'Occupational safety and health',
    'Environmental sanitation',
    'Archaeology',
    'Alternative fuels',
    'Ecotourism',
    'Energy conservation',
    'Sustainable technology',
    'Waste reduction',
    'Water conservation',
    'Sustainable agriculture',
    'Wildlife conservation'
  ];

  static var holidays = [
    'Christmas',
    'New year',
    'Easters',
    'Ramadan',
    'Eid al-fitr',
    'Yam festivals',
    'Calabar festivals',
    'Osun festival',
    'Valentine',
    'Public holidays',
    'National holidays',
    'International holidays'
  ];

  static var lifeAndHistory = [
    'World history',
    'Origin of man',
    'Ancient history',
    'World war I',
    'World war II',
    'Slavery',
    'African-American history',
    'Ancient Egypt',
    'Modern history',
    'Art history',
    'Cold war',
    'Civil and political rights',
    'Women’s history',
    'Economic history',
    'Wars',
    'Culture',
    'Nigeria political history'
  ];

  static var fashion = [
    'Vintage fashion',
    'Casual men fashion',
    'Casual women fashion',
    'Sexy fashion styles',
    'Models',
    'Stylists',
    'Fashion brands',
    'Makeup',
    'Cosmetics',
    'Urban fashion',
    'Street fashion',
    'Exotic fashion style',
    'Fashion trends',
    'Fashion News',
    'Best trends',
    'African fashion',
    'Native styles for men',
    'Women’s style',
    'Men’s wear',
    'Hair care',
    'Fashion columns',
    'Fashion police',
    'Sneakers',
    'Jackets',
    'Blouse',
    'Shoes',
    'Watches',
    'Jewelries',
    'Wardrobe management',
    'Fashion shows',
    'Fashion industry',
    'Fashion entrepreneurs'
  ];

  static var entertainment = [
    'Gist and gossips',
    'Red carpet events',
    'Fashion police',
    'Billboard',
    'Grammy',
    'Mtv base',
    'Concerts',
    'Song release',
    'Albums',
    'Playlists',
    'Celebrities sayings',
    'Partying',
    'Clubbing',
    'Wedding',
  ];
}

class SelectedInterests {
  static var books = [];
  static var music = [];
  static var sport = [];
  static var celebrities = [];
  static var comedy = [];
  static var movies = [];
  static var innovationsandtech = [];
  static var artanddesign = [];
  static var science = [];
  static var business = [];
  static var lifestyle = [];
  static var travel = [];
  static var news = [];
  static var economy = [];
  static var eco = [];
  static var lifeAndHistory = [];
  static var fashion = [];
}
